# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b167a8786f61b72d3a9f624c790e8efea6c12088dcedac57d65ff463206e6dbbfdced0b6c9053e310392b5207c705e10611cd7f2e0113c5add48451c92b7920c

test:
  secret_key_base: 3b4fe3caed28e7fa58ad4bf649e1d6ea4467b41b60449e2f5ff75932221266fca4442055a6fd62ed508ad7cf9a6a4cc356c6716ed5c38b22efea05e2b56c6c74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
